### ISSUE TITLE
number parsing incorrect

### ISSUE THREAD

**Issue by yannick** [iij/mruby-iijson#9]
as per rfc7159 json numbers are not necessairly integers.

thus Numbers should not be parsed into Integer but into Float or at least into Float if Integer Overflows.

**Comment by kazuho** [comment]
My +1 goes to "Float if Integer Overflows".

That would be the best choice not only for performance but also accuracy on 64-bit systems, since mrb_int is 64-bits long by default on such machines. If we always use floats, we would loose some accuracy that we could have gained.
